version: "3.5"

services:
  players_mongodb:
    image: mongo:4.2.6-bionic
    container_name: players_mongodb
    restart: always

  players_uwsgi:
    build: ./docker/players
    container_name: players_uwsgi
    restart: always
    volumes:
      - ./docker/players:/usr/src/app
    environment:
      CONFIGURATION_SETUP: config.DevelopmentConfig
    expose: 
      - "8080"
    depends_on:
      - players_mongodb

#  teams_mongodb:
#    image: mongo:4.2.6-bionic
#    container_name: teams_mongodb
#    restart: always

#  teams_uwsgi:
#    build: ./docker/teams
#    container_name: teams_uwsgi
#    restart: always
#    volumes:
#      - ./docker/teams:/usr/src/app
#    environment:
#      CONFIGURATION_SETUP: config.DevelopmentConfig
#    expose: 
#      - "8080"
#    depends_on:
#      - teams_mongodb

#  rabbit:
#    image: rabbitmq:3.8.3
#    container_name: messages
#    restart: always
#    hostname: messages
#    depends_on:
#      - players_uwsgi

  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: always
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
#      - rabbit
      - players_uwsgi
#      - teams_uwsgi
